name: circular_clip_route
description:
  A page route, which reveals its page by expanding a circular clip from an
  anchor widget.
version: 0.2.0+2
homepage: https://github.com/blaugold/circular_clip_route
repository: https://github.com/blaugold/circular_clip_route
issue_tracker: https://github.com/blaugold/circular_clip_route/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
